Algoritmo "Estrutura repetição enquanto"
// 
// Escreva um algoritmo conte de 0
// até onde o usuário quiser;

//
Var
// Seção de Declarações das variáveis 
cont, valor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont<- 0

Escreva("Quer contar até quanto: ")
Leia(valor)

Enquanto cont < valor faca
         EscrevaL(cont)
         cont <- cont + 1
FimEnquanto

EscrevaL("")
EscrevaL("Terminei de cotar até ", valor)

Fimalgoritmo