Algoritmo "MULTIPLICAÇÃO"
// 
// Solicitar dois números para o usuário
// e mostrar a soma entre eles

Var
// Seção de Declarações das variáveis 

n1, n2, mult: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Informe um número: ")
Leia(n1)

Escreva("Informe outro número: ")
Leia(n2)

     mult <- n1 * n2
     
EscrevaL("A subtração entre os números é: " , mult)

Fimalgoritmo