Algoritmo "DOBRO"
// 
//   Dado um valor, calcular e
//   exibir o dobro do valor.
//
Var
// Seção de Declarações das variáveis 
  valor, dobro: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
EscrevaL(">>> Dobro de um valor >>>")
EscrevaL("")
Escreva("Informe um valor: ")
Leia(valor)

   dobro <- 2*valor

Escreva("O dobro de", valor , " é: ", dobro)
Fimalgoritmo