Algoritmo "OP_RELACIONAIS"
// 
// OPERADORE RELACIONAIS
// Geram como resultados um valor lógico;
// VERDADEIRO OU FALSO

//
//
Var
// Seção de Declarações das variáveis 
a, b, c: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   a<- 2
   b<- 3
   c<- 4
   
   EscrevaL(a>b)
   EscrevaL(a<b)
   EscrevaL(a<>b)
   EscrevaL(c=a+b)
   

Fimalgoritmo